spring:
  profiles:
    active: local
    group:
      local: local, common, oauth
      prod: common, prod, oauth
      dev: dev, oauth

server:
  env: local

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        #        default_batch_fetch_size:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

server:
  port: 8080
  serverAddress: localhost

serverName: local_server

---

spring:
  config:
    activate:
      on-profile: common

springdoc:
  swagger-ui:
    version: 'v1'
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
#  show-login-endpoint: true

jwt:
  secret: aaaabbbsdifqbvaesoioegwaaaabbbsdidsfdsfdfsdfsdfsdfsdfsd

discord:
  url: https://discord.com/api/webhooks/123456781234567812345/zxcvbnmasdfghjklqwertyuiopoiuytrewqlkjhgfdsamnbvcxz
