name: HongikYeolgong2-prod CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set permission for Gradle
        run: chmod +x ./gradlew

      - name: Build Spring Boot (without test)
        run: |
          echo ${{ secrets.APPLICATION_PROD }} | base64 --decode > ./src/main/resources/application-prod.yml
          echo ${{ secrets.APPLICATION_OAUTH }} | base64 --decode > ./src/main/resources/application-oauth.yml
          # echo ${{ secrets.HONGIKYEOLGONG2 }} | base64 --decode > ./src/main/resources/hongikyeolgong2.json
          echo ${{ secrets.OLD_APPLE_KEY_ID }} | base64 --decode > ${{ secrets.OLD_APPLE_KEY_PATH }}
          echo ${{ secrets.NEW_APPLE_KEY_ID }} | base64 --decode > ${{ secrets.NEW_APPLE_KEY_PATH }}
          ./gradlew clean build --exclude-task test

      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hongik-yeolgong-2:prod .
          docker push ${{ secrets.DOCKER_USERNAME }}/hongik-yeolgong-2:prod

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.AWS_ACCESS_ROLE_NAME }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_PROD_HOST }}
          username: ${{ secrets.EC2_PROD_USERNAME }}
          key: ${{ secrets.EC2_PROD_SSH_KEY }}
          port: ${{ secrets.EC2_PROD_SSH_PORT }}
          timeout: 60s
          script: |
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
            sudo docker-compose stop
            sudo docker-compose rm -f
            sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/hongik-yeolgong-2:prod
            sudo docker-compose up -d
